#!/bin/sh
# Runs the provided executable with ksm-preload.so , which enables KSM
# on heap-allocated memory.

# By Brice Arnould <unbrice@vleu.net>
# Copyright (C) 2011 Gandi SAS.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

readonly KSM_PATH=$(cd $(dirname $0) ; pwd)
readonly KSM_SO="${KSM_PATH}/ksm-preload.so"

if [ ! -x "${KSM_SO}" ]; then
    echo "Could not find ${KSM_SO}. Have you compiled it with 'make' ?"
    exit 1
fi

export LD_PRELOAD="${LD_PRELOAD} ${KSM_SO}"
exec "$@"
